### ISSUE TITLE
SmoofyDungeon:default is not a valid flag

### ISSUE THREAD

**Issue by GrimReapaa420** [Yeregorix/SmoofyDungeon#2]
When creating a world wether its Cosmos or Nucleus, it cant find the World-Modifier smoofydungeon:default
Cosmos Error: No values matching pattern
Nucleus: smoofydungeon:default is not a valid flag
i used for nucleus exactly your example code-line
Using the newest version
Smoofydungeon config options are available ingame (/smoofydungeon:sdcfg)

I will try a earlier Version of your plugin now.... for now im really said
EDIT: Not even 1.2.5 of SmoofyDungeon works for me, for both Nucleus AND Cosmos
![image](https://user-images.githubusercontent.com/78499787/126027434-683bad2c-cb7e-4de6-b169-5658e3ca6e60.png)

**Comment by Yeregorix** [comment]
I just tested and it works fine with Nucleus, Cosmos and ProjectWorld.
Nucleus command: `/world create WorldName -m smoofydungeon:default` (you probably missed the `-m`)
Cosmos command: `/cm create WorldName overworld default smoofydungeon:default` (you missed the `default`)

**Comment by GrimReapaa420** [comment]
Nucleus didnt work like that, Cosmos will be tryed asap in 10 min

**Comment by GrimReapaa420** [comment]
Edit: with your code for Cosmos it worked :D thank u very much
